esphome:
  name: esphome-web-98ba44
  friendly_name: ESPHome Web 98ba44
  min_version: 2025.9.0
  name_add_mac_suffix: false
  libraries:
    - lvgl/lvgl@^8.3.11
    - moononournation/Arduino_GFX_Library@^1.4.10

external_components:
  - source:
      type: local
      path: custom_components

esp32:
  variant: esp32s3
  flash_size: 4MB
  framework:
    type: arduino

logger:

api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "esphome-web-98ba44"
    password: "change_me_1234"

captive_portal:

power_supply:
  - id: display_backlight
    pin: GPIO1
    enable_time: 20ms
    keep_on_time: 0ms

lvgl_benchmark:
  backlight_pin: GPIO1
  cs_pin: GPIO45
  clk_pin: GPIO47
  d0_pin: GPIO21
  d1_pin: GPIO48
  d2_pin: GPIO40
  d3_pin: GPIO39

